### ISSUE TITLE
Possible to output combined keyboard and mouse?  (re: weeCee PS/2 input)

### ISSUE THREAD

**Issue by sofakng** [rasteri/HIDman#12]
Thanks for the excellent project!

Would you consider adding a feature (to both the 'legacy' PS2 and newer AXP versions) to output both keyboard and mouse on a single PS/2 cable?  For example, your weeCee only has a single PS/2 input and requires both signals on the same cable.

Thanks!

**Comment by rasteri** [comment]
I already plan to add this feature - the ports are already wired up for this.

**Comment by sofakng** [comment]
Great, thanks so much!  I posted a couple of other questions on Vogons if you have a minute to check.  Thanks again!

**Comment by rasteri** [comment]
This is now implemented
