### ISSUE TITLE
Restore PS/2 version functionality

### ISSUE THREAD

**Issue by sofakng** [rasteri/HIDman#14]
Sorry to bother you again...  Can you confirm this is the correct orientation for the LED?  (green dot towards PCB)

![IMG_7012](https://github.com/rasteri/HIDman/assets/2228499/add06126-891b-4234-9734-47dde8705436)

**Comment by rasteri** [comment]
yeah I think that's right.
unfortunately the PS/2 version will need some firmware tweaks to work again - the current code only works for AXP...

I should have some time to work on integrating them soon

**Comment by sofakng** [comment]
Ahhh, OK.  That probable explains why I was able to flash the chip but it doesn't seem to work.  I'll keep an eye on any updates.  Thanks!

**Comment by yarodin** [comment]
Same story here. Waiting fixed firmware for PS/2 version.

**Comment by rasteri** [comment]
This has been fixed - latest firmware supports PS/2 version again.
