### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by DFL1973** [rasteri/HIDman#15]
Hello, thanks for sharing, but I can´t get the source compiled under Linux or Windows.

make
sdcc -c -V -mmcs51 --model-large --stack-auto --xram-size 0x1600 --xram-loc 0x0200 --code-size 0xEFFF -I/ -DFREQ_SYS=48000000 -DBOARD_AXP -DOPT_DEFAULT  -o build/main.rel main.c
+ F:\SDCC\bin\sdcpp.exe -nostdinc -Wall -std=c11 -I"/" -D"FREQ_SYS=48000000" -D"BOARD_AXP" -D"OPT_DEFAULT" -obj-ext=.rel -D__SDCC_STACK_AUTO -D__SDCC_CHAR_UNSIGNED -D__SDCC_MODEL_LARGE -D__SDCC_INT_LONG_REENT -D__SDCC_FLOAT_REENT -D__SDCC=3_6_0 -D__SDCC_VERSION_MAJOR=3 -D__SDCC_VERSION_MINOR=6 -D__SDCC_VERSION_PATCH=0 -DSDCC=360 -D__SDCC_REVISION=9615 -D__SDCC_mcs51 -D__STDC_NO_COMPLEX__=1 -D__STDC_NO_THREADS__=1 -D__STDC_NO_ATOMICS__=1 -D__STDC_NO_VLA__=1 -D__STDC_ISO_10646__=201409L -D__STDC_UTF_16__=1 -D__STDC_UTF_32__=1 -isystem "F:\SDCC\bin\..\include\mcs51" -isystem "F:\SDCC\bin\..\include"  "main.c"
main.c:163: syntax error: token -> 'uint32_t' ; column 12
main.c:169: syntax error: token -> 'uint8_t' ; column 11
main.c:183: syntax error: token -> 'uint8_t' ; column 15
(tons of other errors)

Versions:
SDCC -v
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/TININative/ds400/hc08/s08/stm8 3.5.0 #9253 (Apr  3 2018) (Linux)
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8 3.6.0 #9615 (MINGW32)

Thanks

**Comment by vtrucco** [comment]
Fixed after installing SDCC 4.3.0, thanks

**Comment by DFL1973** [comment]
Fixed after installing SDCC 4.3.0, thanks
