### ISSUE TITLE
Collaboration request for Gamepad/Joystick to UART

### ISSUE THREAD

**Issue by relaxibus** [rasteri/HIDman#16]
Hi, I found your repository. I was working on a similar project, however to convert USB gamepads and joysticks to a specific UART protocol (SERaero) in order o use it to control RC models. I paid a developer to adapt the UART output to the SERaero, however it is not perfect and the guy has no more time. I‘m not a coder, so looking for others working on the CH559. Would you be interested to join the projects?

**Comment by rasteri** [comment]
Not at this moment in time. By all means start your own project using hidman as a base though.
