### ISSUE TITLE
Suggestion: Document PCB ordering process

### ISSUE THREAD

**Issue by Sebazzz** [rasteri/HIDman#38]
I can read circuit diagrams, I can solder, but I've never ordered a custom PCB before. Suggestion to document what options to choose at the PCB vendor (e.g. PCBway) and how to export the Kicad files in a format PCBWay reads. Thanks!

**Comment by rasteri** [comment]
I'm working on it. update soon

**Comment by Sebazzz** [comment]
Thanks!

**Comment by rasteri** [comment]
OK my video about HIDman includes info on how to order everything : https://youtu.be/44tg6oXGmYI?t=614
